### ISSUE TITLE
doesn't work offline

### ISSUE THREAD

**Issue by NNTeamProject** [NNTeam2018/Tabel_Periodik#9]
![image](https://user-images.githubusercontent.com/38391639/39243888-837adc0e-48c1-11e8-99de-0241319f493f.png)

**Comment by elberthomax** [comment]
it's me

**Comment by stevelukis** [comment]
Ummm... It is a website. Of course you need to be online.

Change the value of  `DATA_URL` in script/main.js to the absolute path of the local document.xml for offline usage. Maintain the status quo. The real site should be online.
